# Generated by Django 5.2.8 on 2025-11-25 11:00

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(help_text='Nom de la bourse', max_length=200)),
                ('organisme', models.CharField(help_text='Organisme proposant la bourse', max_length=200)),
                ('description', models.TextField(help_text='Description de la bourse')),
                ('conditions', models.TextField(help_text="Conditions d'éligibilité")),
                ('niveaux_concernes', models.JSONField(default=list, help_text="Niveaux concernés (ex: ['COLLEGE', 'LYCEE'])")),
                ('montant', models.CharField(blank=True, help_text='Montant de la bourse', max_length=100)),
                ('deadline', models.DateField(blank=True, help_text='Date limite de candidature', null=True)),
                ('url_candidature', models.URLField(blank=True, help_text='Lien pour candidater')),
                ('documents_requis', models.TextField(blank=True, help_text='Documents nécessaires')),
                ('contact', models.TextField(blank=True, help_text='Informations de contact')),
                ('est_active', models.BooleanField(default=True, help_text='Bourse actuellement disponible')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bourse',
                'verbose_name_plural': 'Bourses',
                'ordering': ['-est_active', 'deadline'],
            },
        ),
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Ex: 3ème, Terminale S', max_length=50, unique=True)),
                ('niveau', models.CharField(choices=[('PRIMAIRE', 'Primaire'), ('COLLEGE', 'Collège'), ('LYCEE', 'Lycée')], help_text='Niveau scolaire', max_length=20)),
                ('serie', models.CharField(blank=True, help_text='Série pour le lycée (A, C, D, L, OSE, S)', max_length=10, null=True)),
                ('ordre', models.IntegerField(help_text='Ordre de la classe (1=11ème, 22=Terminale S)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(22)])),
                ('description', models.TextField(blank=True, help_text='Description de la classe')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Classe',
                'verbose_name_plural': 'Classes',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Ex: Mathématiques', max_length=100, unique=True)),
                ('code', models.CharField(help_text='Ex: MATH', max_length=20, unique=True)),
                ('icone', models.CharField(default='📚', help_text="Emoji ou nom d'icône", max_length=50)),
                ('couleur', models.CharField(default='#3B82F6', help_text='Code couleur hexadécimal', max_length=7)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Matière',
                'verbose_name_plural': 'Matières',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Orientation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(help_text='Nom du métier/carrière', max_length=200)),
                ('description', models.TextField(help_text='Description du métier')),
                ('filiere', models.CharField(help_text='Filière recommandée (ex: Scientifique, Littéraire)', max_length=100)),
                ('series_recommandees', models.JSONField(default=list, help_text="Séries recommandées (ex: ['S', 'C', 'D'])")),
                ('debouches', models.TextField(help_text='Débouchés professionnels')),
                ('competences_requises', models.TextField(help_text='Compétences nécessaires')),
                ('niveau_etudes', models.CharField(help_text="Niveau d'études requis (ex: Bac+3, Bac+5)", max_length=100)),
                ('salaire_moyen', models.CharField(blank=True, help_text='Salaire moyen estimé', max_length=100)),
                ('perspectives', models.TextField(blank=True, help_text="Perspectives d'évolution")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Orientation',
                'verbose_name_plural': 'Orientations',
                'ordering': ['titre'],
            },
        ),
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre_chapitre', models.CharField(help_text='Titre du chapitre', max_length=200)),
                ('objectifs', models.TextField(help_text='Objectifs pédagogiques')),
                ('competences', models.TextField(help_text='Compétences à acquérir')),
                ('ordre', models.IntegerField(default=1, help_text='Ordre du chapitre dans le programme', validators=[django.core.validators.MinValueValidator(1)])),
                ('trimestre', models.IntegerField(default=1, help_text='Trimestre (1, 2 ou 3)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('duree_estimee', models.IntegerField(blank=True, help_text='Durée estimée en heures', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classe', models.ForeignKey(help_text='Classe concernée', on_delete=django.db.models.deletion.CASCADE, related_name='programmes', to='students.classe')),
                ('matiere', models.ForeignKey(help_text='Matière concernée', on_delete=django.db.models.deletion.CASCADE, related_name='programmes', to='students.matiere')),
            ],
            options={
                'verbose_name': 'Programme',
                'verbose_name_plural': 'Programmes',
                'ordering': ['classe__ordre', 'matiere__nom', 'ordre'],
                'unique_together': {('classe', 'matiere', 'ordre')},
            },
        ),
        migrations.CreateModel(
            name='Ressource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(help_text='Titre de la ressource', max_length=200)),
                ('description', models.TextField(help_text='Description de la ressource')),
                ('type_contenu', models.CharField(choices=[('TEXTE', 'Texte'), ('PDF', 'PDF'), ('VIDEO', 'Vidéo'), ('QUIZ', 'Quiz'), ('AUDIO', 'Audio'), ('LIEN', 'Lien externe')], default='TEXTE', help_text='Type de contenu', max_length=20)),
                ('contenu', models.TextField(blank=True, help_text='Contenu textuel (pour type TEXTE)')),
                ('url_fichier', models.URLField(blank=True, help_text='URL du fichier (PDF, vidéo, etc.)', null=True)),
                ('fichier', models.FileField(blank=True, help_text='Fichier uploadé', null=True, upload_to='ressources/%Y/%m/')),
                ('tags', models.JSONField(blank=True, default=list, help_text='Tags pour la recherche')),
                ('auteur', models.CharField(blank=True, help_text='Auteur de la ressource', max_length=100)),
                ('source', models.CharField(blank=True, help_text='Source de la ressource', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('programme', models.ForeignKey(help_text='Programme associé', on_delete=django.db.models.deletion.CASCADE, related_name='ressources', to='students.programme')),
            ],
            options={
                'verbose_name': 'Ressource',
                'verbose_name_plural': 'Ressources',
                'ordering': ['-created_at'],
            },
        ),
    ]
