# Generated by Django 5.2.8 on 2025-11-23 20:52

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True, help_text="Contenu complet de l'article."),
        ),
        migrations.AddField(
            model_name='content',
            name='category',
            field=models.CharField(choices=[('LANGUE', 'Formation linguistique'), ('SCOLAIRE', 'Éducation scolaire'), ('ORIENTATION', 'Orientation professionnelle'), ('CANDIDATURE', 'Techniques de candidature'), ('ENTREPRENEURIAT', 'Entrepreneuriat & Gestion'), ('PRO', 'Formation professionnelle'), ('SANTE', 'Santé & Hygiène'), ('PERSO', 'Développement personnel'), ('CITOYEN', 'Vie Citoyenne'), ('SOCIAL', 'Sensibilisation Sociale'), ('ECOLOGIE', 'Environnement & Écologie'), ('SECURITE', 'Sécurité (Globale)'), ('FINANCE', 'Finances personnelles'), ('ECONOMIE', 'Économie & Industrie'), ('AUTRE', 'Autre')], default='AUTRE', max_length=20),
        ),
        migrations.AddField(
            model_name='content',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Brouillon'), ('PENDING', 'En attente de validation'), ('PUBLISHED', 'Publié')], default='DRAFT', max_length=10),
        ),
        migrations.AlterField(
            model_name='content',
            name='description',
            field=models.TextField(blank=True, help_text='Courte description pour les cartes.'),
        ),
        migrations.AlterField(
            model_name='content',
            name='file_url',
            field=models.FileField(blank=True, null=True, upload_to='contents/'),
        ),
    ]
