# Generated by Django 5.2.8 on 2025-11-24 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0003_content_body_content_category_content_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='is_monetized',
            field=models.BooleanField(default=False, help_text='Le créateur souhaite monétiser ce contenu'),
        ),
        migrations.AddField(
            model_name='content',
            name='license_accepted',
            field=models.BooleanField(default=False, help_text='Le créateur a accepté la licence de distribution'),
        ),
    ]
