# Generated by Django 5.2.8 on 2025-11-27 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0004_content_is_monetized_content_license_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='level',
            field=models.CharField(blank=True, help_text='Niveau cible (ex: Débutant, Lycée...)', max_length=100),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(help_text='Type de question (ex: Grammaire, Vocabulaire)', max_length=50)),
                ('prompt', models.TextField(help_text="L'énoncé de la question")),
                ('answer', models.TextField(help_text='La réponse attendue')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='contents.content')),
            ],
        ),
    ]
