# Generated by Django 5.2.8 on 2026-01-05 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0005_content_level_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='quiz',
            field=models.JSONField(blank=True, default=list, help_text='Liste des questions du quiz au format JSON'),
        ),
    ]
