# Generated by Django 5.2.15 on 2026-06-29 19:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0006_content_quiz'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('is_correct', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='content',
            name='competency',
            field=models.CharField(blank=True, help_text='Compétence visée par le contenu.', max_length=180),
        ),
        migrations.AddField(
            model_name='content',
            name='language',
            field=models.CharField(choices=[('fr', 'Français'), ('mg', 'Malgache'), ('fr-mg', 'Français et malgache')], default='fr', max_length=8),
        ),
        migrations.AddField(
            model_name='content',
            name='moderation_reason',
            field=models.TextField(blank=True, help_text='Motif de refus ou note de modération.'),
        ),
        migrations.AddField(
            model_name='content',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='slug',
            field=models.SlugField(blank=True, max_length=280),
        ),
        migrations.AddField(
            model_name='content',
            name='subject',
            field=models.CharField(blank=True, help_text='Matière ou domaine principal.', max_length=120),
        ),
        migrations.AddField(
            model_name='content',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='content',
            name='target_audience',
            field=models.CharField(blank=True, help_text='Public cible principal.', max_length=120),
        ),
        migrations.AlterField(
            model_name='content',
            name='file_type',
            field=models.CharField(choices=[('VIDEO', 'Video'), ('AUDIO', 'Audio'), ('TEXT', 'Text/PDF'), ('PDF', 'PDF')], max_length=10),
        ),
        migrations.AlterField(
            model_name='content',
            name='quiz',
            field=models.JSONField(blank=True, default=list, help_text='Ancien format de quiz JSON conservé pour compatibilité'),
        ),
        migrations.AlterField(
            model_name='content',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Brouillon'), ('PENDING', 'Soumis à validation'), ('SUBMITTED', 'Soumis à validation'), ('APPROVED', 'Validé'), ('REFUSED', 'Refusé'), ('PUBLISHED', 'Publié'), ('ARCHIVED', 'Archivé')], default='DRAFT', max_length=12),
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('level', models.CharField(blank=True, max_length=100)),
                ('subject', models.CharField(blank=True, max_length=120)),
                ('competency', models.CharField(blank=True, max_length=180)),
                ('language', models.CharField(choices=[('fr', 'Français'), ('mg', 'Malgache'), ('fr-mg', 'Français et malgache')], default='fr', max_length=8)),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('PENDING', 'Soumis à validation'), ('PUBLISHED', 'Publié'), ('ARCHIVED', 'Archivé')], default='DRAFT', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to=settings.AUTH_USER_MODEL)),
                ('content', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qcm_quizzes', to='contents.content')),
            ],
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(default=0)),
                ('max_score', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='contents.quiz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('single_choice', 'Choix unique'), ('multiple_choice', 'Choix multiple')], default='single_choice', max_length=20)),
                ('prompt', models.TextField()),
                ('explanation', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('points', models.PositiveIntegerField(default=1)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='contents.quiz')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='QuizAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(default=False)),
                ('earned_points', models.PositiveIntegerField(default=0)),
                ('selected_choices', models.ManyToManyField(blank=True, to='contents.answerchoice')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='contents.quizattempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contents.quizquestion')),
            ],
        ),
        migrations.AddField(
            model_name='answerchoice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='contents.quizquestion'),
        ),
    ]
