# Generated by Django 5.2.15 on 2026-06-15 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('STUDENT', 'Student'), ('JOB_SEEKER', 'Job Seeker'), ('CREATOR', 'Content Creator'), ('MODERATOR', 'Moderator'), ('ADMIN', 'Administrator')], default='STUDENT', help_text='User role in the platform', max_length=20),
        ),
    ]
